### ISSUE TITLE
Can you show a before/after screenshot on README of what this workbench does?

### ISSUE THREAD

**Issue by luzpaz** [APEbbers/TitleBlock-WB#12]
When viewing in the addon manager, it would be super convenient to have a visual way to grok what this workbench does.

**Comment by APEbbers** [comment]
Hi, I've added a picture which shows the interactions between the titleblock in TechDraw drawing, the spreadsheet table and Excel.
Do you think this is clear enough? The exact before and after is basically an empty titleblock and a filled titleblock. So I think this will show a bit more what the workbench does.

If you want more pictures, or a different approach, please let me know, i'll update the readme.

I've also added the license section to the readme and removed the "pychache" folder.
